### PR TITLE
example code of recursive proof

### PR DESCRIPTION
**Pull request by jzaki**
pure ts module to show recursive proof. Intended to use export+codegen via scripts, but execution doesn't verify inner proofs. A future pr will extract the export+codegen example for it's own example.

### CODE REVIEW

**Comment by jzaki** [comment]
Related: https://github.com/noir-lang/noir/pull/4563

**Comment by jzaki** [comment]
Modifying to be recursive

**Comment by jzaki** [comment]
Closes https://github.com/AztecProtocol/dev-rel/issues/197

**Comment by catmcgee** [comment]
hey @jzaki this is for this repo - https://github.com/noir-lang/noir-examples/tree/master/recursion/packages/noir/recursion

right now it does something similar to your example here  - although yours is much more concise :)

I think @signorecello's idea was to have a more practical example, eg a game

**Comment by jzaki** [comment]
@catmcgee They are quite different.

**Comment by Savio-Sou** [comment]
Would be great to get you guys' help on updating https://noir-lang.org/docs/how_to/how-to-recursion, perhaps following the review and merging of this PR.

**Review by critesjosh — COMMENTED** [review]
@jzaki wdyt about adding some more detail to the README (e.g. about the structure of the repo)? I think it'd be helpful to give a short description of what `sumLib`, `sum`, `recurseNode`, and `recurseLeaf` all do, and how they fit together in `main.ts`.

**Review by critesjosh — APPROVED** [review]
nice!

**Pull request merged**
