### PR TITLE
chore: sandbox tutorial + token update

### PR DESCRIPTION
**Pull request by benesjan**
Token contract and the token tutorial were outdated so I updated it.

### CODE REVIEW

**Comment by catmcgee** [comment]
hey @benesjan this is awesome thank you!
can you resolve conflicts so we can merge?

**Comment by benesjan** [comment]
@catmcgee it looks like the token tutorial was completely remove from the repo. Should I just close the PR?

**Comment by benesjan** [comment]
@critesjosh np, I think this tutorial was very useful because deploying a token and minting token balances is such a common setup for anything DeFi related. @harshnambiar just needed this tutorial for his project.

But I think if we decide to keep them around it should be in normal docs and in monorepo because it's true that maintaining them here is pain.

**Comment by catmcgee** [comment]
@benesjan we're going to keep this for now and find an automation that allows us to use #include_code snippets. we may move this into the monorepo or have a submodule or something.

tutorials are back  so let's reopen this

**Pull request merged**
